### ISSUE TITLE
Absence of audio track prevents testing AV sync

### ISSUE THREAD

**Issue by nicholas-fr** [cta-wave/Test-Content-Generation#14]
Test content is missing an audio track (cannot test AV sync). 
For video tests, propose to add a switching set with a single audio track with mezzanine audio encoded using AAC core media profile.

**Comment by jpiesing** [comment]
December 15th
This is an issue with the script Rodolphe wrote so deferred until staffing issues are resolved.

**Comment by rbouqueau** [comment]
Could you please give us a pointer on the audio available content (or how to generate it) ? I don't see anything in http://dash.akamaized.net/WAVE/Mezzanine.

**Comment by jpiesing** [comment]
> Could you please give us a pointer on the audio available content (or how to generate it) ? I don't see anything in http://dash.akamaized.net/WAVE/Mezzanine.

The .mp4 files have both video and audio in them.

**Comment by rbouqueau** [comment]
Excellent, then it indeed looks like a bug. I'm taking this issue.

**Comment by jpiesing** [comment]
> Excellent, then it indeed looks like a bug. I'm taking this issue.

I know it's a little confusing - these files would ideally have been prores but ffmpeg prores output didn't seem to work properly. See https://github.com/cta-wave/mezzanine/issues/15

**Comment by rbouqueau** [comment]
What was the plan about audio for the single track switching sets? Is audio only for the ss X1?

**Comment by jpiesing** [comment]
> What was the plan about audio for the single track switching sets? Is audio only for the ss X1?

We need content for both of the following;
a) video-only switching set tests (8.5, 8.11)
b) tests for CMAF Presentations that need both video and audio (9.x)

For the CMAF presentation test content, we can use the audio that's in the mezzanine content & just encode it as HE-AAC. This audio also has beeps added that should be synchronised with the flashes in the audio

@rbouqueau Does this answer the question or have I missed something?

**Comment by rbouqueau** [comment]
Thank you Jon. I think it is clear enough for now.

**Comment by jpiesing** [comment]
Tests for 8.x don't need audio. If the MPD includes audio then this should be ignored by the HTML+JS code for that test. The observation framework should ignore it.


Jon


________________________________

**Comment by jpiesing** [comment]
> I'm still a bit confused as to the intended make up of the 8.x test content.
> https://github.com/cta-wave/dpctf-tests/blob/master/sample.csv seems to imply that the 'avc' tests don't have audio (there is no audio MPD listed). However, there is an audio Representation within the "video" MPD, that the Test Runner does play.

For the 8.x tests for AVC (or indeed any video media profile), the audio in those MPDs could be ignored.

> In the future, is this audio intended to be part of the test analysis?

Not for the 8.x tests.

**Comment by jpiesing** [comment]
@nicholas-fr As far as I can see, the content includes both video and audio Adaptation Sets. Do you agree? Can this issue be closed?

**Comment by andyburras** [comment]
I'm still unclear on the usage of this audio. It's not required for the 8.x tests.
I thought for the 9.x Presentation playback tests, that Test Runner used one MPD for the video and a different MPD for the audio, or is that not the case?

**Comment by jpiesing** [comment]
> I'm still unclear on the usage of this audio. It's not required for the 8.x tests.
> I thought for the 9.x Presentation playback tests, that Test Runner used one MPD for the video and a different MPD for the audio, or is that not the case?

For the 8.x tests, the audio can be ignored.
For the 9.x tests, the same MPD can be used for both video & audio.

**Comment by nicholas-fr** [comment]
Resolved, with the caveat that ss1 cannot be used for AV sync testing as the same audio track is used for all the different video representations with different frame rates (not to imply that ss1 was intended for AV sync testing, just a clarification for the avoidance of doubt).
