### ISSUE TITLE
Missing frames at end of test streams

### ISSUE THREAD

**Issue by nicholas-fr** [cta-wave/Test-Content-Generation#15]
Test content seems to be missing the last frames (tested with DASH.js):
- 60fps ends on frame 3599 instead of 3601 (3600 with content + last red frame signalling end of content).
- 30fps half frame rate ends on frame 3595 (missing 3597, 3599 + last red frame).

**Comment by jpiesing** [comment]
December 15th meeting
Alternatively the frames could be there & dash.js may not be playing them.
dash.js may terminate playback at the last point there are both video and audio.
@nicholas-fr Check in a video editor if the last frames are actually there.

**Comment by nicholas-fr** [comment]
Checked with VLC v3.0.11 and the last frames are actually present (although VLC also doesn't always play the last frame).
So this was due to DASH client behaviour and not a test stream issue.
Following the explanation Will gave in today's call, I'll have a look into the mezzanine content generation.
It seems plausible that this is in fact caused by how the start/end frames are inserted (without audio).

**Comment by nicholas-fr** [comment]
I did not find anything in the mezzanine generation that would explain this issue.
As such, the most plausible explanation is that it's due to client behaviour.
