### ISSUE TITLE
Combination of full and half frame rates in same switching set

### ISSUE THREAD

**Issue by nicholas-fr** [cta-wave/Test-Content-Generation#16]
The impact of implementing tests combining full and half frame rates in the same switching set on the observation framework and the mezzanine content needs to be considered. 

Using 50Hz or 60Hz mezzanine content for 25Hz or 30Hz content results in frames being skipped and gaps in the sequence of frame numbers and QR codes. Creating 25Hz or 30Hz mezzanine content would avoid skipped frames but would have other consequences (e.g. different frame counters between full & half frame rate tracks present within the same switching set).

**Comment by jpiesing** [comment]
December 15th meeting
Preference for 25Hz and 30Hz content to be derived from 25Hz and 30Hz mezzanine content with no missing frames.
Is there space in the QR code to encode the frame rate? Yes but would mean recoding everything.
Next steps
@nicholas-fr Will upload a 30Hz mezzanine.
Eurofins to comment here.

**Comment by nicholas-fr** [comment]
30Hz mezzanine streams (270p to 1080p) have been encoded and uploaded:
https://dash-large-files.akamaized.net/WAVE/Mezzanine/

**Comment by jpiesing** [comment]
> 30Hz mezzanine streams (270p to 1080p) have been encoded and uploaded:
> https://dash-large-files.akamaized.net/WAVE/Mezzanine/

@nicholas-fr Does the JSON file listing all the media automatically update?

**Comment by nicholas-fr** [comment]
The JSON file doesn't list the [mezzanine content](https://dash-large-files.akamaized.net/WAVE/Mezzanine/).
The [JSON file](https://dash.akamaized.net/WAVE/vectors/database.json) lists the [test streams generated](https://dash.akamaized.net/WAVE/vectors/avc_sets/), and is updated automatically when test streams are generated using the [run-all.py script](https://github.com/cta-wave/Test-Content-Generation/blob/master/run-all.py).
New test streams are not automatically created when new mezzanine files are added. Hope that clarifies.

**Comment by jpiesing** [comment]
> [](https://github.com/cta-wave/Test-Content-Generation/blob/master/run-all.py).

Thanks. Sorry.

**Comment by nicholas-fr** [comment]
I'm glad you asked, as it prompted me to check how it was actually created/updated in the latest test content generation scripts.

**Comment by yanj-github** [comment]
Yes, we prefer to have mezzanine contents for each frame rate (e.g: 25Hz and 30Hz content to be derived from 25Hz and 30Hz mezzanine content). Thanks @nicholas-fr for getting 30Hz mezzanine streams done.
And we would like to have the frame rate encoded in QR code please.

**Comment by jpiesing** [comment]
> Yes, we prefer to have mezzanine contents for each frame rate (e.g: 25Hz and 30Hz content to be derived from 25Hz and 30Hz mezzanine content). Thanks @nicholas-fr for getting 30Hz mezzanine streams done.
> And we would like to have the frame rate encoded in QR code please.

Thanks. @nicholas-fr has finished until the new year but modifying the contents of the QR code will get looked at then & all the mezzanine content regenerated.

**Comment by nicholas-fr** [comment]
We will need to agree on the composition of the text string including the frame rate.
The related mezzanine issue with a proposal for this can be found [here](https://github.com/cta-wave/mezzanine/issues/21).

**Comment by jpiesing** [comment]
https://dash-large-files.akamaized.net/WAVE/vectors/avc_sets/15_30_60/ss1/stream.mpd includes 2 x 60Hz and 1 x 15Hz representation as well as the more common 30Hz representations.

@nicholas-fr Can this issue be closed?

**Comment by nicholas-fr** [comment]
Resolved, ss1 contains all 3 frame rates of the 15/30/60 family.
