### ISSUE TITLE
Longer stream for AV sync testing

### ISSUE THREAD

**Issue by nicholas-fr** [cta-wave/Test-Content-Generation#17]
Currently we generate 60s test streams. For AV sync testing purposes we may want to generate a longer test stream, e.g. 15 min.
Propose to add this to the backlog.

**Comment by jpiesing** [comment]
December 15th meeting
No input so indeed is added to the backlog.

**Comment by gitwjr** [comment]
Remains open. Waiting for other issues to clear.

**Comment by rbouqueau** [comment]
If https://github.com/cta-wave/Test-Content/issues/39 (which depends on https://github.com/cta-wave/mezzanine/issues/46) are cleared, then it means that we should be able to process long content duration quite easily. Waiting for the status on the other issues.

**Comment by nicholas-fr** [comment]
As updated in https://github.com/cta-wave/mezzanine/issues/46 and https://github.com/cta-wave/mezzanine/issues/14 the mezzanine content is now available for this in mezzanine release v4:
https://dash-large-files.akamaized.net/WAVE/Mezzanine/releases/4/tos_LD1_1920x1080@30_7200.mp4
https://dash-large-files.akamaized.net/WAVE/Mezzanine/releases/4/croatia_LD1_1920x1080@25_7200.mp4

**Comment by rbouqueau** [comment]
Online and referenced by database.json.

**Comment by rbouqueau** [comment]
Can we close?

**Comment by gitwjr** [comment]
@louaybassbouss Keep open until it is tested and validated.

**Comment by jpiesing** [comment]
An error has been reported with this test - https://github.com/cta-wave/dpctf-tests/issues/144

**Comment by rbouqueau** [comment]
I've just checked and the content plays continuous or seeks fine:

![image](https://github.com/cta-wave/Test-Content-Generation/assets/1917976/30bfd88c-cd7e-4a48-90dd-91627ff25f4a)

Waiting for more details from @yanj-github.

**Comment by yanj-github** [comment]
@rbouqueau thanks the content is fine. The timeout is on test runner end. The test is on default timeout at 10 minutes it is fine for most of test but not long duration.

**Comment by jpiesing** [comment]
Since the error was not with the stream, we can close.
