### ISSUE TITLE
Bundle Test Content in a ZIP file

### ISSUE THREAD

**Issue by louaybassbouss** [cta-wave/Test-Content-Generation#19]
This enables the test runner to easily download test content. Example ZIP files are available in [this folder](http://dash.akamaized.net/WAVE/ContentModel/SinglePeriod/Fragmented/).

**Comment by jpiesing** [comment]
FYI this issue arises from discussions in the December 15th meeting arising from https://github.com/cta-wave/dpctf-tests/issues/7 and https://github.com/cta-wave/dpctf-tests/issues/9 .

**Comment by louaybassbouss** [comment]
Any update on this issue?

**Comment by rbouqueau** [comment]
What is the granularity of the zip files? Would one zip file per switching set (i.e. per subfolder) be ok?

**Comment by jpiesing** [comment]
> What is the granularity of the zip files? Would one zip file per switching set (i.e. per subfolder) be ok?

@louaybassbouss ?

**Comment by louaybassbouss** [comment]
> > What is the granularity of the zip files? Would one zip file per switching set (i.e. per subfolder) be ok?
> 
> @louaybassbouss ?

@jpiesing the Zip should contain the manifest and all related audio/video files/segments (of course keep the file structure as it is). Basically, each item in [database.json](https://dash.akamaized.net/WAVE/vectors/database.json) should have a reference to the corresponding zip file. This [download script](https://github.com/cta-wave/dpctf-tests/blob/master/download-content.py) parses database.json and checks if the [zipPath](https://github.com/cta-wave/dpctf-tests/blob/master/download-content.py#L28) property for each item exists. If it is available, it downloads and extracts the zip from the location in `zipPath`.

**Comment by jpiesing** [comment]
> @jpiesing the Zip should contain the manifest and all related audio/video files/segments (of course keep the file structure as it is). Basically, each item in [database.json](https://dash.akamaized.net/WAVE/vectors/database.json) should have a reference to the corresponding zip file. This [download script](https://github.com/cta-wave/dpctf-tests/blob/master/download-content.py) parses database.json and checks if the [zipPath](https://github.com/cta-wave/dpctf-tests/blob/master/download-content.py#L28) property for each item exists. If it is available, it downloads and extracts the zip from the location in `zipPath`.

@rbouqueau Is this clear enough for you?

**Comment by rbouqueau** [comment]
That's clear. For each subfolder (#22) I will create a zip file.

**Comment by rbouqueau** [comment]
Content was uploaded e.g. https://dash.akamaized.net/WAVE/vectors/avc_sets/t1.zip (t1 to t34) or https://dash.akamaized.net/WAVE/vectors/avc_sets/ss1.zip

**Comment by louaybassbouss** [comment]
> Content was uploaded e.g. https://dash.akamaized.net/WAVE/vectors/avc_sets/t1.zip (t1 to t34) or https://dash.akamaized.net/WAVE/vectors/avc_sets/ss1.zip

@rbouqueau  thanks a lot I just downloaded t1.zip LGTM :).  One minor thing is there a reason to have the `output` folder in the zip file?  Do you know when [database.json](https://dash.akamaized.net/WAVE/vectors/database.json) will be updated to include the `zipPath`.

**Comment by rbouqueau** [comment]
> One minor thing is there a reason to have the output folder

I'll fix it.

> Do you know when database.json will be updated to include the zipPath.

The database.json is actually updated (though not with the zipPath). But the cache policy on this server makes it unusable for me. It drives me crazy. Will do soon.

**Comment by louaybassbouss** [comment]
> > One minor thing is there a reason to have the output folder
> 
> I'll fix it.
> 
> > Do you know when database.json will be updated to include the zipPath.
> 
> The database.json is actually updated (though not with the zipPath). But the cache policy on this server makes it unusable for me. It drives me crazy. Will do soon.

Thanks @rbouqueau we will test beginning of next week is not urgent for today.

**Comment by rbouqueau** [comment]
zipPath implemented.

**Comment by jpiesing** [comment]
@louaybassbouss  Can this be closed now?

**Comment by louaybassbouss** [comment]
> @louaybassbouss Can this be closed now?

@jpiesing LGTM issue can closed

**Comment by jpiesing** [comment]
@rbouqueau Please either close this issue if you think that's OK or be clear what still needs to be done.
