### ISSUE TITLE
Provide list of available audio/video content e.g. in a JSON file

### ISSUE THREAD

**Issue by louaybassbouss** [cta-wave/Test-Content-Generation#20]
This will help the download script in the test runner to identify available content to download. Each entry of the JSON file includes the URLs of the video and audio content (ZIP files).

**Comment by nicholas-fr** [comment]
The test content that has already been generated is located here:
https://dash.akamaized.net/WAVE/vectors/

[This JSON file](https://dash.akamaized.net/WAVE/vectors/database.json) details the content options of each switching set, the relative path to the MPD and for each track, the resolution, frame rate, bitrate and source mezzanine content.

This currently requires use of the MPD to download the audio/video content.

**Comment by jpiesing** [comment]
@louaybassbouss is https://dash-large-files.akamaized.net/WAVE/vectors/database.json OK for you?

Can this issue be closed?

**Comment by louaybassbouss** [comment]
> @louaybassbouss is https://dash-large-files.akamaized.net/WAVE/vectors/database.json OK for you?
> 
> Can this issue be closed?

@jpiesing  LGTM issue can be closed

**Comment by louaybassbouss** [comment]
May 25th meeting 
Close issue
