### ISSUE TITLE
naming convention for output folders

### ISSUE THREAD

**Issue by rbouqueau** [cta-wave/Test-Content-Generation#22]
Hi @louaybassbouss

@nicholas-fr and I got an email discussion about the opportunity to find a better naming the output folders. At the moment these folders are called '1', '2', etc. (see http://dash.akamaized.net/WAVE/index.html?cache=clear)

Nicholas mentioned that we could think of a naming convention related to the use of the content. For example
- ss1 for switching set 1 that contains multiple tracks (now referred to as switching set X in #13, previously X1)
-  't1 .. tn' for switching sets generated with single tracks, where n is the test stream ID from the [spreadsheet (row 2)](https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/edit#gid=0).

This is just a suggestion. Please let us know if this has some added value for you.

**Comment by jpiesing** [comment]
@rbouqueau @louaybassbous @nicholas-fr 

Looking at where we want to be in a few months time, I could see a hierarchy something like this ...

1st level - WAVE media profiles (codecs)
2nd level - only for video, 50Hz / 60Hz (?)
3rd level - CMAF switching sets (as per the original proposal from @rbouqueau )

**Comment by nicholas-fr** [comment]
So for example, would this give the following?

**AVC 15/30/60Hz**:
https://dash.akamaized.net/WAVE/vectors/avc/15_30_60/ss1/
https://dash.akamaized.net/WAVE/vectors/avc/15_30_60/t1/
[...]
https://dash.akamaized.net/WAVE/vectors/avc/15_30_60/tn/

**AVC 14.985/29.97/59.94Hz**:
https://dash.akamaized.net/WAVE/vectors/avc/14.985_29.97_59.94/ss1/
https://dash.akamaized.net/WAVE/vectors/avc/14.985_29.97_59.94/t1/
[...]
https://dash.akamaized.net/WAVE/vectors/avc/14.985_29.97_59.94/tn/

**AVC 12.5/25/50Hz**:
https://dash.akamaized.net/WAVE/vectors/avc/12.5_25_50/ss1/
https://dash.akamaized.net/WAVE/vectors/avc/12.5_25_50/t1/
[...]
https://dash.akamaized.net/WAVE/vectors/avc/12.5_25_50/tn/

**HEVC 15/30/60Hz**:
https://dash.akamaized.net/WAVE/vectors/hevc/15_30_60/ss1/
https://dash.akamaized.net/WAVE/vectors/hevc/15_30_60/t1/
[...]
https://dash.akamaized.net/WAVE/vectors/hevc/15_30_60/tn/

**Comment by jpiesing** [comment]
> So for example, would this give the following?

That's the sort of thing I had in mind.

**Comment by louaybassbouss** [comment]
> > So for example, would this give the following?
> 
> That's the sort of thing I had in mind.

Also fine for me

**Comment by jpiesing** [comment]
Since everyone seems to be OK with this proposal & it's been implemented for 15_30_60, can the issue be closed?

**Comment by jpiesing** [comment]
May 25th
Encryption addressed.
