### ISSUE TITLE
change CMAF segment durations for AVC from 2s and 5s

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content-Generation#24]
Test 9.4 needs streams where video and audio segments can be aligned.
We either make dedicated streams for test 9.4 or change all streams to enable video and audio segments to be aligned.

From https://websites.fraunhofer.de/video-dev/why-and-how-to-align-media-segments-for-abr-streaming/ , this suggests we might change 2s and 5s to the following;

For 25 & 50Hz video - 1.92s and either 3.84s or 6.4s
For 30 & 60Hz video - 1.60s and 4.8s

Thoughts?

**Comment by louaybassbouss** [comment]
@dsilhavy FYI

**Comment by jpiesing** [comment]
I've added a comment to the spreadsheet that was used to track the content options. https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/edit?usp=sharing

**Comment by gitwjr** [comment]
Closed. Potentially open a new issue if it is determined the content used by Fraunhofer for splicing is not correct.
