### ISSUE TITLE
Generate 12.5/25/50 new content

### ISSUE THREAD

**Issue by rbouqueau** [cta-wave/Test-Content-Generation#29]

**Comment by rbouqueau** [comment]
addressed in 739a844d6e7db167de17d51785cf06f3c4f845f2

**Comment by louaybassbouss** [comment]
@rbouqueau  initial test in desktop browser is completed and successful ;) --> https://github.com/cta-wave/dpctf-tests/issues/44#issuecomment-884887728

**Comment by rbouqueau** [comment]
Perfect, thanks for letting us know!
