### ISSUE TITLE
Generate fractional fps new content

### ISSUE THREAD

**Issue by rbouqueau** [cta-wave/Test-Content-Generation#30]

**Comment by rbouqueau** [comment]
addressed in dfe8e305db42961cf45fdaee9d343288f5c4d2ed

**Comment by louaybassbouss** [comment]
@rbouqueau  initial test in desktop browser is completed and successful ;) --> https://github.com/cta-wave/dpctf-tests/issues/44#issuecomment-884887728

**Comment by rbouqueau** [comment]
Perfect, thanks for letting us know!
