### ISSUE TITLE
Integrate encryption to the python scripts

### ISSUE THREAD

**Issue by rbouqueau** [cta-wave/Test-Content-Generation#31]

**Comment by jpiesing** [comment]
I can see lots of encrypted content (cenc) in dash.akamaized.net/WAVE/vectors/avc_sets/15_30_60 .
@rbouqueau  Is this done now?

**Comment by rbouqueau** [comment]
It is not automatized. I put the keys [on the repo](https://github.com/cta-wave/Test-Content-Generation/blob/master/DRM.xml) and the manual instructions are [here](https://github.com/cta-wave/dpctf-tests/issues/12#issuecomment-778804472).

**Comment by jpiesing** [comment]
> It is not automatized. I put the keys [on the repo](https://github.com/cta-wave/Test-Content-Generation/blob/master/DRM.xml) and the manual instructions are [here](https://github.com/cta-wave/dpctf-tests/issues/12#issuecomment-778804472).

So are you waiting for the conclusion of https://github.com/cta-wave/dpctf-tests/issues/12 before updating the scripts to make it automatic?

**Comment by rbouqueau** [comment]
Not only but that's indeed the only technological point preventing automation.

**Comment by rbouqueau** [comment]
Done in 7d95f9571a89a90185ac37e1fd9472215a0420d2

**Comment by rbouqueau** [comment]
closing
