### ISSUE TITLE
streams t27 and t29 not 16:9

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content-Generation#32]
Streams t27 and t29 are not 16:9, 213/120 could be a rounding error but 180/101 is a bit further off.

t27/stream.mpd:  &lt;AdaptationSet segmentAlignment="true" maxWidth="852" maxHeight="480" maxFrameRate="30" par="213:120" lang="und" startWithSAP="1" contentType="video" segmentProfiles="cmfs, cmff">

t28/stream.mpd:  &lt;AdaptationSet segmentAlignment="true" maxWidth="768" maxHeight="432" maxFrameRate="30" par="16:9" lang="und" startWithSAP="1" contentType="video" segmentProfiles="cmfs, cmff">

t29/stream.mpd:  &lt;AdaptationSet segmentAlignment="true" maxWidth="720" maxHeight="404" maxFrameRate="30" par="180:101" lang="und" startWithSAP="1" contentType="video" segmentProfiles="cmfs, cmff">

**Comment by jpiesing** [comment]
@haudiobe Do 852x480 and 720x404 require special treatment to come out as 16:9?

**Comment by rbouqueau** [comment]
Good catch. If the intent was not to test SAR changes then this is likely an issue.

The code includes the possibility to force the SAR. However this was not explicitly specified in [this table](https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/edit#gid=0). Hence not linked. I think we should add an explicit column with the SAR ([here](https://github.com/cta-wave/Test-Content-Generation/blob/master/switching_sets_single_track.csv)).

**Comment by jpiesing** [comment]
My intent was not to test SAR changes but I defer to @haudiobe  and also I don't know what CMAF says about them.

**Comment by jpiesing** [comment]
May 25th meeting
@haudiobe to comment.

**Comment by jpiesing** [comment]
t27 = https://dash.akamaized.net/WAVE/vectors/avc_sets/15_30_60/t27/stream.mpd
t29 = https://dash.akamaized.net/WAVE/vectors/avc_sets/15_30_60/t29/stream.mpd

**Comment by jpiesing** [comment]
I've looked at the MPDs in the HbbTV DASH test suite;

- In the tests for 852x480, all have par 16:9 and sar 640:639.
- In the tests for 720x404, some have par 720:404 with sar 1:1, others have par 16:9 with sar 404:405.

Is sar or an equivalent included in CMAF?

**Comment by rbouqueau** [comment]
NB @jpiesing : it doesn't change the content but the links you gave are deprecated. The latest links are:
- t27 = https://dash.akamaized.net/WAVE/vectors/2021-06-11/avc_sets/15_30_60/t27/stream.mpd
- t29 = https://dash.akamaized.net/WAVE/vectors/2021-06-11/avc_sets/15_30_60/t29/stream.mpd

The latest links can be retrieved from https://cta-wave.github.io/Test-Content/

**Comment by jpiesing** [comment]
@louaybassbouss  If we have some MPDs with representations sar different from 1:1 (e.g. 640:639 or 404:405), what would the test player do?

**Comment by louaybassbouss** [comment]
> @louaybassbouss If we have some MPDs with representations sar different from 1:1 (e.g. 640:639 or 404:405), what would the test player do?

@jpiesing the video element covers the whole screen, if the video aspect ratio is not the same as the screen aspect ratio, then you will see some back areas (either top/bottom or left/right). Do you have an MPD for me?

**Comment by jpiesing** [comment]
> @jpiesing the video element covers the whole screen, if the video aspect ratio is not the same as the screen aspect ratio, then you will see some back areas (either top/bottom or left/right). Do you have an MPD for me?

Yes. 
https://dash.akamaized.net/WAVE/vectors/2021-06-11/avc_sets/15_30_60/t27/stream.mpd

and

https://dash.akamaized.net/WAVE/vectors/2021-06-11/avc_sets/15_30_60/t29/stream.mpd

Look at the par and sar for both of these.

**Comment by haudiobe** [comment]
DPCTF: 
- Streams not exactly 16:9
- Valid test content, but annotation is needed => @poolec may be able to check

**Comment by jpiesing** [comment]
December 6th 2022: Discussed and is just an artfeact. Closing as no new input received.
