### ISSUE TITLE
<AssetIdentifier schemeIdUri="urn:cta:org:wave-test-mezzanine:unique-id" value="0"/>

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content-Generation#34]
The MPDs in vectors/avc_sets/15-30-60 all seem to include the following;
```
<AssetIdentifier schemeIdUri="urn:cta:org:wave-test-mezzanine:unique-id" value="0"/>
```
Is there any documentation of what this means?
Is it just a placeholder?
If it's just a placeholder, what can it best be used for?

**Comment by rbouqueau** [comment]
No idea. It existed before I even arrived. Let's see at our next call if anyone knows what it means. Otherwise we can remove.

**Comment by jpiesing** [comment]
I wonder if it might be a (partial) solution to Thomas's request in https://github.com/cta-wave/Test-Content-Generation/issues/3 ?

**Comment by cta-source** [comment]
I don't know about it being a (partial) solution to Thomas's request (yea or nay).  I do recall a conversation about something that might be related.  Could it be equivalent to the specification level of the mezz annotations?  We discussed locking down a spec for mezzanine annotations -- in process, see [Mezzanine Issue #34](https://github.com/cta-wave/mezzanine/issues/31#issuecomment-814903531).  This field would appear to identify the mezzanine "version level".  

If this field has no other purpose, perhaps we can use if that way?

**Comment by jpiesing** [comment]
It might be worth considering using this (or something like it) for information on the content options that are not already somewhere else in the MPD - which would otherwise only be accessible using stream analysis tools.

- with and without picture timing SEI message.
- with and without VUI timing information.
- Sample entry, see CMAF clause 9.4.1.2
- CMAF Fragment durations
- Initialization Constraints
- Fragments containing one or multiple moof/mdat pairs

Resolution, frame rate and bitrate are in the MPD.

Perhaps a comma separated list of name-value pairs?

Or is this abuse of AssetIdentifier?

**Comment by cta-source** [comment]
Perhaps we need two tags:
1) Tag for the spec version of the Test Content Specification (covers mezzanine annotations and some requirements of encoded content, such as file name format)--this spec version is so that the test suite can programmatically determine what annotations and other details apply, especially if they change.  I've dropped the above tag into the draft specification for now, but I don't believe it is the correct id necessarily.  
2) Tag(s) for information on content options that are not already in the manifest, as JP points out above (with/without picture timing SEI message; with/without VUI timing info; etc.)

**Comment by cta-source** [comment]
This seems fairly straightforward so I've dropped the items #1 and #2 in the immediately-above "Perhaps we need two tags" comment into the draft Test Content Format spec.  We still need the actual tag definitions, though.

**Comment by jpiesing** [comment]
May 25th meeting
Wider issue of how to include content metadata in the MPD.
If metadata is in the MPD, what if the content is used without a manifest? 
Don't see being used without any manifest, if translating to M3U then content metadata could also be translated.

**Comment by gitwjr** [comment]
12-06-12 meeting: Closed. The identifier remains but is not being used. It can be removed in the next iteration.
