### ISSUE TITLE
streams t18 and t19 not required?

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content-Generation#35]
Streams t18 and t19 have been created in https://goo.gl/maps/hmDRmTHvHF9ey3828 but were not listed in the spreadsheet at https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/edit?usp=sharing .

I left a gap between t17 and t20 in case other content options were found.

Am I missing something?

**Comment by rbouqueau** [comment]
You're right. My mistake.
