### ISSUE TITLE
README instructions need reviewing and updating

### ISSUE THREAD

**Issue by andyburras** [cta-wave/Test-Content-Generation#36]
Instructions state:

> How to generate the content
>     Download the files from https://1drv.ms/w/s!AiNJEPgowJnWgbpZesbLvglzCXVlSg?e=4ZFRyB, be sure to pick different fingerprints
> 

Bu this goes to https://onedrive.live.com/view.aspx?resid=D699C028F8104923!23897&ithint=file%2cdocx&authkey=!AHrGy74Jcwl1ZUo which appears to be an extract from the DPCTF spec ?

**Comment by rbouqueau** [comment]
The whole README needs a refresh. Would you agree to rename the issue? I'll have a look.

**Comment by andyburras** [comment]
Thanks.... Issue name changed

**Comment by rbouqueau** [comment]
I made a pass.

**Comment by andyburras** [comment]
Looks much better thanks.
