### ISSUE TITLE
Incorrect copyright notice

### ISSUE THREAD

**Issue by andyburras** [cta-wave/Test-Content-Generation#37]
I noticed the MPD generation is adding a CTA WAVE Copyright `"<Copyright>CTA WAVE</Copyright>".`

I think this is in breach of the Tears of Steel and Big Buck Bunny Creative Commons Attribution licenses. We're free to copy and redistribute in any medium or format, and to remix, transform, and build upon the material. But it must retain the Creative Commons Attribution 3.0 license, and the original producers and licenses must be attributed.

We should probably have such a notice on the https://dash.akamaized.net/WAVE/ and https://dash.akamaized.net/WAVE/index.html too.

**Comment by nicholas-fr** [comment]
For reference, the licenses associated with the source content are present here:
https://dash-large-files.akamaized.net/WAVE/Original/tearsofsteel_4k_LICENSE.txt
https://dash-large-files.akamaized.net/WAVE/Original/DVB_PQ10_VandV_LICENSE.txt

**Comment by mbergman42** [comment]
This is a bit complicated because CTA Legal determined that a click-through End User License Agreement will be needed as well.  See Issue #38, which picks up on the need for a click-through and has the necessary license text.  This license text directly addresses the copyright requirements mentioned here, and meets obligations for the ToS and BBB CCA licenses.  This issue should be closed when the MPD generation is updated to fit.  I'll pursue this question, "what should replace the copyright statement flagged here".

**Comment by jpiesing** [comment]
Open source licenses like the creative commons ones used here permit re-distribution of the content so people will be able to share the content bypassing the click-through EULA. Given this, I think it would be sensible to include CTA information in more than one place.
Also when I look at the creative commons license, CTA is required to provide a link to that license. 

For the MPDs based on tears of steel, I recommend replacing;

<Copyright>CTA WAVE</Copyright>

with either

<Copyright>Blender Foundation | mango.blender.org</Copyright>

or use the full text of https://dash.akamaized.net/WAVE/Original/tearsofsteel_4k_LICENSE.txt

Certainly we should remove the incorrect copyright before we re-generate the streams.

**Comment by mbergman42** [comment]
CTA Legal says, please use this for embedded copyright in place of the "CTA WAVE" copyright statement, where appropriate:


© [Big Buck Bunny](https://peach.blender.org/about/) (2008) and [Tears of Steel](https://mango.blender.org/about/) (2012) by Blender Institute, credited to Ton Roosendaal and Ian Hubert, used and licensed under [Creative Commons Attribution 3.0 Unported (CC BY 3.0)](https://creativecommons.org/licenses/by/3.0/) by the Consumer Technology Association (CTA)® / annotated, encoded and compressed from original.  © Croatia (2008), credited to EBU, used and licensed under [Creative Commons Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/) by the Consumer Technology Association (CTA)® / annotated, encoded and compressed from original.

As Jon points out, links must be included in the text.

**Comment by nicholas-fr** [comment]
We need separate text for each piece of source content, so I've separated it out into 3 parts. Could CTA legal confirm this is the text they wanted for BBB and ToS in particular? 

I made 2 changes:
- I removed Ian Hubert for the BBB text, as he is not listed in the [team credits](https://peach.blender.org/the-team/).
- The date was wrong for the EBU content, so I updated that.

Here are the 3 separate texts:
- BBB: © [Big Buck Bunny](https://peach.blender.org/about/) (2008) by Blender Institute, credited to Ton Roosendaal, used and licensed under [Creative Commons Attribution 3.0 Unported (CC BY 3.0)](https://creativecommons.org/licenses/by/3.0/) by the Consumer Technology Association (CTA)® / annotated, encoded and compressed from original.

- ToS: © [Tears of Steel](https://mango.blender.org/about/) (2012) by Blender Institute, credited to Ton Roosendaal and Ian Hubert, used and licensed under [Creative Commons Attribution 3.0 Unported (CC BY 3.0)](https://creativecommons.org/licenses/by/3.0/) by the Consumer Technology Association (CTA)® / annotated, encoded and compressed from original.

- Croatia: © Croatia (2019), credited to EBU, used and licensed under [Creative Commons Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/) by the Consumer Technology Association (CTA)® / annotated, encoded and compressed from original.

Once these are confirmed to be OK (or corrected), then I'll include them in the mezzanine metadata, which could then be used when generating the test vectors.

**Comment by mbergman42** [comment]
Yes, this is great.  Please use this.

Mike Bergman
Consumer Technology Association, producer of CES®
d: +1(703) 907-4366
m: +1(609) 865-4402

**Comment by rbouqueau** [comment]
Could someone summarize for me what we need to put in the DASH manifest? Do we leave a mention to CTA WAVE?

**Comment by nicholas-fr** [comment]
I will include the license text in the mezzanine metadata.
You could extract the license text to include in the MPD from that, if that helps?

For example, for mezzanine tos_A1_480x270@15_60.mp4, you would extract the license string from tos_A1_480x270@15_60.json:
I.e.
` "license": "\u00a9 Tears of Steel (https://mango.blender.org/about/) (2012) by Blender Institute, credited to Ton Roosendaal and Ian Hubert, used and licensed under Creative Commons Attribution 3.0 Unported (CC BY 3.0) (https://creativecommons.org/licenses/by/3.0/) by the Consumer Technology Association (CTA)\u00ae / annotated, encoded and compressed from original."`

**Comment by rbouqueau** [comment]
Ok. I'll probably extract them manually for the first batch. Since https://github.com/cta-wave/mezzanine/issues/35 is done, do you confirm it is safe for me to regenerate the test content?

**Comment by jpiesing** [comment]
> Since [cta-wave/mezzanine#35](https://github.com/cta-wave/mezzanine/issues/35) is done, do you confirm it is safe for me to regenerate the test content?

Comments crossed in the cloud. Yes - see https://github.com/cta-wave/Test-Content/issues/16

**Comment by rbouqueau** [comment]
Done in 739a844d6e7db167de17d51785cf06f3c4f845f2

**Comment by rbouqueau** [comment]
@all See https://dash.akamaized.net/WAVE/vectors/2021-07-05/avc_sets/15_30_60/t1/stream.mpd

Please close if ok.

**Comment by jpiesing** [comment]
> @ALL See https://dash.akamaized.net/WAVE/vectors/2021-07-05/avc_sets/15_30_60/t1/stream.mpd
> 
> Please close if ok.

@mbergman42  What do you think?

**Comment by mbergman42** [comment]
Looks good to me, thanks.

Mike Bergman
Consumer Technology Association, producer of CES®
d: +1(703) 907-4366
m: +1(609) 865-4402
