### ISSUE TITLE
generating unused encrypted streams

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content-Generation#39]
We seem to be generating a encrypted versions of all streams - which I don't believe we need. We have the following tests;
- 8.12 - Regular playback of encrypted content
I expect this would just use stream t1
- 8.13 - Restricted Splicing of Encrypted Content
I cannot understand this one. Is it the same as 8.8 but with all content encrypted?
- 8.14 Sequential Playback of Encrypted and Non-Encrypted Baseline Content
- Is this the same as 8.8 but with the main content encrypted but with the inserted content in the clear?

If this is correct then the only encrypted streams we need are;
- t1
- the streams for 8.8 (which don't currently have a name/label)

Specifically we don't need t2 and higher or ss1.

What am I missing?

**Comment by jpiesing** [comment]
@rbouqueau I see the newly updated database.json still includes encrypted versions of all(?) unecncrypted streams. This is way more than we need - I think it's only t1 that is needed (as well as whatever we end up with for splicing).

**Comment by rbouqueau** [comment]
@jpiesing Thanks, I'm fixing the json and I'll fix the python script soon

**Comment by rbouqueau** [comment]
@jpiesing See https://cta-wave.github.io/Test-Content/, click on the CENC tab. Please close if ok.

**Comment by jpiesing** [comment]
Looks good to me.
