### ISSUE TITLE
Generate a content using mezzanine with black background area

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/Test-Content-Generation#42]
A new test mezzanine is created here https://github.com/cta-wave/mezzanine/issues/36#issuecomment-882644468
Can you generate a test content with this mezzanine which has a black background area for QR codes please?

**Comment by jpiesing** [comment]
> Yes. Where is the full mezzanine content folder? https://dash-large-files.akamaized.net/WAVE/Mezzanine/under_review/2021-07-19/ is incomplete.

That is intended. It's just an experiment to see how much of a difference it makes. There's no need for all the streams.

**Comment by rbouqueau** [comment]
Generated here: https://dash-large-files.akamaized.net/WAVE/vectors/2021-07-26/avc_sets/15_30_60/

**Comment by louaybassbouss** [comment]
> @yanj-github Do you understand the process for connecting HTML+JS and test content sufficiently well to use this directly or do you need help from @louaybassbouss ?

We need to add new combination to the tests.csv. I can do it if you tell me which combination you need. is `sequencial-track-playback` with `t33` ok for you?

**Comment by yanj-github** [comment]
Thanks all. Yes @louaybassbouss I just need it as 8.2 test. I would like to have the old t33 as well, if you can keep the old one but add the new one please?

**Comment by louaybassbouss** [comment]
> Thanks all. Yes @louaybassbouss I just need it as 8.2 test. I would like to have the old t33 as well, if you can keep the old one but add the new one please?

Yes I will not touch the existing tests I will add a new folder  `avc_15_30_60-2021-07-26-online` (and one for `avc_15_30_60-2021-07-26-local`) with one test combination `sequential-track-playback`x`t33`. I will do it tomorrow and let you know.

**Comment by louaybassbouss** [comment]
> Thanks all. Yes @louaybassbouss I just need it as 8.2 test. I would like to have the old t33 as well, if you can keep the old one but add the new one please?

@yanj-github a new test `sequential-track-playback`x[`t33`](https://dash-large-files.akamaized.net/WAVE/vectors/2021-07-26/avc_sets/15_30_60/t33/stream.mpd) is generated in the new folder `avc_15_30_60-2021-07-26-online`. Please let me know if you have questions.

**Comment by yanj-github** [comment]
The new test is not working, I am not sure if this is issue on test or the contents but I tried the following mpd on dash player it didnt work. Can anyone help to investigate please? Not sure why we used dash-large-files.akamaized.net?
https://dash-large-files.akamaized.net/WAVE/vectors/2021-07-26/avc_sets/15_30_60/t33/stream.mpd

**Comment by rbouqueau** [comment]
> I tried the following mpd on dash player it didnt work. Can anyone help to investigate please?

The following works for me, how is it for you?

https://reference.dashif.org/dash.js/latest/samples/dash-if-reference-player/index.html?mpd=https://dash-large-files.akamaized.net/WAVE/vectors/2021-07-26/avc_sets/15_30_60/t33/stream.mpd

> Not sure why we used dash-large-files.akamaized.net?

Because people explicitly complained about CORS when using the www.gpac-licensing.com server. Would you have expected another server or URL?

**Comment by yanj-github** [comment]
> 
> 
> > I tried the following mpd on dash player it didnt work. Can anyone help to investigate please?
> 
> The following works for me, how is it for you?
> 
> https://reference.dashif.org/dash.js/latest/samples/dash-if-reference-player/index.html?mpd=https://dash-large-files.akamaized.net/WAVE/vectors/2021-07-26/avc_sets/15_30_60/t33/stream.mpd
> 
> > Not sure why we used dash-large-files.akamaized.net?
> 
> Because people explicitly complained about CORS when using the [www.gpac-licensing.com](http://www.gpac-licensing.com) server. Would you have expected another server or URL?

I have following error. Is this might be a permission issue please? 
Error Dash.js :25
https://dash-large-files.akamaized.net/WAVE/vectors/2021-07-26/avc_sets/15_30_60/t33/stream.mpd is not available

**Comment by rbouqueau** [comment]
Could someone else give a try please? Can you read:
- https://dash-large-files.akamaized.net/WAVE/vectors/2021-07-26/avc_sets/15_30_60/t33/stream.mpd
- https://reference.dashif.org/dash.js/latest/samples/dash-if-reference-player/index.html?mpd=https://dash-large-files.akamaized.net/WAVE/vectors/2021-07-26/avc_sets/15_30_60/t33/stream.mpd
?

**Comment by yanj-github** [comment]
> 
> 
> Could someone else give a try please? Can you read:
> 
>     * https://dash-large-files.akamaized.net/WAVE/vectors/2021-07-26/avc_sets/15_30_60/t33/stream.mpd

I can see this.

> 
>     * https://reference.dashif.org/dash.js/latest/samples/dash-if-reference-player/index.html?mpd=https://dash-large-files.akamaized.net/WAVE/vectors/2021-07-26/avc_sets/15_30_60/t33/stream.mpd
>       
But not this one.

@louaybassbouss  can you kindly help to check please?

**Comment by cta-source** [comment]
Directly accessing https://dash-large-files.akamaized.net/WAVE/vectors/2021-07-26/avc_sets/15_30_60/t33/stream.mpd in Chrome works, I can read the MPD file.

With the dash.js link below, I got Error 25 also:

“https://dash-large-files.akamaized.net/WAVE/vectors/2021-07-26/avc_sets/15_30_60/t33/stream.mpd is not available”

Mike Bergman
Consumer Technology Association, producer of CES®
d: +1(703) 907-4366
m: +1(609) 865-4402

**Comment by rbouqueau** [comment]
Thanks. What about https://reference.dashif.org/dash.js/latest/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/WAVE/vectors/2021-07-26/avc_sets/15_30_60/t33/stream.mpd ?

**Comment by yanj-github** [comment]
> 
> 
> Thanks. What about https://reference.dashif.org/dash.js/latest/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/WAVE/vectors/2021-07-26/avc_sets/15_30_60/t33/stream.mpd ?

Thank you very much. this is working. 

@louaybassbouss Can you kinldy help to change the mpd link please?

**Comment by louaybassbouss** [comment]
> > Thanks. What about https://reference.dashif.org/dash.js/latest/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/WAVE/vectors/2021-07-26/avc_sets/15_30_60/t33/stream.mpd ?
> 
> Thank you very much. this is working.
> 
> @louaybassbouss Can you kinldy help to change the mpd link please?

@yanj-github  done :)
