### ISSUE TITLE
1920x1080p50/p60 is outside the cmfhd / cfhd media profile

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content-Generation#43]
The cmfhd / chfd media profile does not include 1920x1080p50/p60 but this is included as one of the CMAF tracks in the Switching Set for test 8.5 Switching Set Playback and 8.11.

![image](https://user-images.githubusercontent.com/8490792/133091044-50c23c02-20f6-420d-925c-512573833ae4.png)

Some options include;
- Remove 1920x1080p50/p60 from tests 8.5/8.11 and do not test 1920x1080p50/p60 at all
- Remove 1920x1080p50/p60 from tests 8.5/8.11 but add another repetition of Sequential Track Playback with 1920x1080p50/p60.
- Keep the current Switching Set unchanged and create a new one otherwise identical but without 1920x1080p50/p60. Add a repetition of 8.5 with the new Switching Set.
- Modify the playout[] to try 1920x1080p50/p60 first and modify the test to discard that CMAF track if there's an error.
- Keep the current Switching Set unchanged and modify the code for 8.5/8.11 to query media capabilities for 1920x1080p50/p60 support and to ignore that CMAF track if it's not supported. (I have no idea if media capabilities in the real world support this level of testing - I fear not).

Other options may exist.

We should continue testing 1920x1080p50/p60 so the first of these options should be discarded.

**Comment by jpiesing** [comment]
@louaybassbouss Do you know if there's a viable real-world mechanism (excl. try it & see) to identify if a device supports AVC profile 4.0 but not higher & hence not 1920x1080p50/p60?

**Comment by louaybassbouss** [comment]
> @louaybassbouss Do you know if there's a viable real-world mechanism (excl. try it & see) to identify if a device supports AVC profile 4.0 but not higher & hence not 1920x1080p50/p60?

@jpiesing you can use [MediaSource.isTypeSupported(mimeType)](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource/isTypeSupported) to check if specific codec+profile is supported or not (Return value: '_A boolean value which is true if the browser feels that it can probably play media of the specified type_...' ). You need to try all codec+profile combinations higher than AVC 4.0 to check if they are supported or not. `isTypeSupported()` does not include resolution and framerate. You can also use [Media Capabilities API](https://www.w3.org/TR/media-capabilities/) ->  [VideoConfiguration](https://www.w3.org/TR/media-capabilities/#videoconfiguration) which allows you to consider other capabilities like `width`, `height`, `framerate`, ...

**Comment by jpiesing** [comment]
> @jpiesing you can use [MediaSource.isTypeSupported(mimeType)](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource/isTypeSupported) to check if specific codec+profile is supported or not (Return value: '_A boolean value which is true if the browser feels that it can probably play media of the specified type_...' ). You need to try all codec+profile combinations higher than AVC 4.0 to check if they are supported or not. `isTypeSupported()` does not include resolution and framerate. You can also use [Media Capabilities API](https://www.w3.org/TR/media-capabilities/) -> [VideoConfiguration](https://www.w3.org/TR/media-capabilities/#videoconfiguration) which allows you to consider other capabilities like `width`, `height`, `framerate`, ...

I thought isTypeSupported couldn't be relied on for accurate information, particularly not for profiles within a codec. Am I confusing it with canPlayType?

**Comment by louaybassbouss** [comment]
> > @jpiesing you can use [MediaSource.isTypeSupported(mimeType)](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource/isTypeSupported) to check if specific codec+profile is supported or not (Return value: '_A boolean value which is true if the browser feels that it can probably play media of the specified type_...' ). You need to try all codec+profile combinations higher than AVC 4.0 to check if they are supported or not. `isTypeSupported()` does not include resolution and framerate. You can also use [Media Capabilities API](https://www.w3.org/TR/media-capabilities/) -> [VideoConfiguration](https://www.w3.org/TR/media-capabilities/#videoconfiguration) which allows you to consider other capabilities like `width`, `height`, `framerate`, ...
> 
> I thought isTypeSupported couldn't be relied on for accurate information, particularly not for profiles within a codec. Am I confusing it with canPlayType?

Yes this is correct both `isTypeSupported` and `canPlayType` do not give a safe answer (this is the reason I copied the sentence from the spec  '_A boolean value which is true if the browser feels that it can probably play media of the specified type..._'). Since we use MSE API to append media content to the buffer,  we prefer to use MSE.isTypeSupported and not HTMLMediaElement.canPlayType. Media Capabilities API should actually solve these issues but we saw some inconstancies with the API in some browsers. FYI dash.js uses `MSE.isTypeSupported`. @dsilhavy feel free to comment if I missed something.

**Comment by jpiesing** [comment]
@louaybassbouss @dsilhavy Would it be reasonable to modify the test runner to not use the 1920x1080p50/p60 stream (aka stream 20) if MSE.isTypeSupported would return false for AVC 4.2?

**Comment by jpiesing** [comment]
Closing as 'chdf' was approved for inclusion in the 2022 WAVE CSTF specification, CTA5001-E.
