### ISSUE TITLE
database.json update process

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/Test-Content-Generation#45]
On the each run the script regenerates databse.json.
Instead, can it just update the part that is new or replace what only what is updated please?
The databse.json will have dolby contnet information it might get replaced after new content get generated.

**Comment by gitwjr** [comment]
2022-06-12 meeting: Peter will review with Yan. Yan will add comment after she reviews the issue and the associated process.

**Comment by jpiesing** [comment]
@yanj-github Are we going to do any more on this or can we close it?

**Comment by yanj-github** [comment]
I am happy to close this issue. The process is agreed merging instead of overwritting.
