### ISSUE TITLE
encoding 30s test streams

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content-Generation#48]
@nicholas-fr has produced a mezzanine stream with 30s duration in response to https://github.com/cta-wave/dpctf-tests/issues/56 .
As described in https://github.com/cta-wave/dpctf-tests/issues/56#issuecomment-1044223473, 

1.     Nicholas creates a 1920x1080 mezzanine stream with duration 30s. No other resolutions have a 30s mezzanine.
2.     The current streams t1 to t17 inclusive (all of which are 1920x1080) are all re-encoded from this 30s mezzanine but otherwise unchanged.
3.     Streams t20 onwards all remain at 60s (note that t20 is the only 1920x1080 one of these).
4.     Since t1 is now 30s duration, a new stream is generated which is the same as the current t1. This is used only in the Switching Set tests. Call it t19 or t35 or t20 (& renumber existing t20 to t21 and so on).
5.     Encrypted stream is re-encoded based on the 30s mezzanine
6.     No change to splicing tests.

@rbouqueau can you take care of 2, 4 and 5?

**Comment by rbouqueau** [comment]
It's on my todo. However I am away this week and back only next Wednesday afternoon.

**Comment by rbouqueau** [comment]
For 4., would it be possible to amend the [test code sparse Matrix - AVC](https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/edit#gid=0) with a new t19 column then? I don't have write access to the document.

**Comment by jpiesing** [comment]
> For 4., would it be possible to amend the [test code sparse Matrix - AVC](https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/edit#gid=0) with a new t19 column then? I don't have write access to the document.

Done.

**Comment by rbouqueau** [comment]
I confirm this was ok for me.

**Comment by rbouqueau** [comment]
Done in the latest release.

**Comment by jpiesing** [comment]
Closed.
