### ISSUE TITLE
Stream t10 incorrectly generated?

### ISSUE THREAD

**Issue by Lis-TV** [cta-wave/Test-Content-Generation#49]
The stream should be without VUI timing information, but timing_info_present_flag is set to 1, with num_units_in_tick = 1; timescale=50 and fixed_frame_rate_flag = 0

wget https://dash.akamaized.net/WAVE/vectors/2021-09-09/avc_sets/12.5_25_50/t10/croatia_L1_1920x1080@25_60_dash_track1_init.mp4 --no-check-certificate

wget wget https://dash.akamaized.net/WAVE/vectors/2021-09-09/avc_sets/12.5_25_50/t10/croatia_L1_1920x1080@25_60_dash_track1_0.m4s --no-check-certificate

**Comment by rbouqueau** [comment]
There were indeed issues in the pic_timing sei versus vui timing info (both in the generation and the validation scripts). The latest content should be ok.

Commit reference for the fix: 32f04dd34d8f701edd7f4be068d5522e22a5cb9b.

**Comment by gitwjr** [comment]
2022-11-22: Closed based on Nicholas' validation testing of 2022-10-17 test vectors release.
