### ISSUE TITLE
AVC 4.0 vs 4.2, CFHD vs CFHF

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content-Generation#52]
It is reported that all (most?) of the AVC test vectors are 4.2.
If the CMAF profile indicated is 'CFHD' then this is incompatible with the CMAF spec.

![image](https://user-images.githubusercontent.com/8490792/173007092-1c91f4fc-422d-4ef3-b2b1-981661a41fce.png)

If the CMAF profile indicated is 'CFHF' then this is compatible with CMAF but we should discuss whether this what we actually want.

I don't remember ever discussing AVC profile and level & it's not in the sparse matrix.

The only time 4.0 vs 4.2 came up concerns streams t20 and t23, see https://github.com/cta-wave/Test-Content-Generation/issues/43 which need to be 4.2 as thay are p50.

**Comment by rbouqueau** [comment]
See my [comment](https://github.com/cta-wave/Test-Content-Generation/issues/53#issuecomment-1168644668) in #53.

**Comment by rbouqueau** [comment]
@jpiesing In the sparse matrix I think only t20 needs to be level 4.2. All other can be encoded with level 4.0.

**Comment by jpiesing** [comment]
> @jpiesing In the sparse matrix I think only t20 needs to be level 4.2. All other can be encoded with level 4.0.

I wasn't sure about 720p50/60.

**Comment by nicholas-fr** [comment]
Just to confirm:
720p50/60 AVC only requires level 4.0
1080p50/60 AVC requires level 4.2

**Comment by Lis-TV** [comment]
_720p50/60 AVC only requires level 4.0
1080p50/60 AVC requires level 4.2_

Confirm.

**Comment by rbouqueau** [comment]
Should have been solved by 107d6ea1aa98f515833a7e8c7fdf7298410a3246.

**Comment by nicholas-fr** [comment]
Resolved in the latest test content, see https://github.com/cta-wave/Test-Content/issues/40#issuecomment-1310031376.
I believe this issue can be closed.

**Comment by gitwjr** [comment]
2022-11-22: Closed based on Nicholas' validation testing of 2022-10-17 test vectors release.
