### ISSUE TITLE
T16, no B-frame

### ISSUE THREAD

**Issue by Lis-TV** [cta-wave/Test-Content-Generation#54]
The  test code sparse Matrix - AVC requires for T16 B-Frames to be present:

`Fragment contains multiple chunks (p-frame to p-frame with b-frames)`

But when I used `ffprobe -i whole_content.mp4 -show_frames` there was only I-frames ( `pict_type=I` ) and P-frames ( `pict_type=P` )

**Comment by rbouqueau** [comment]
Where can I find the "sparse Matrix - AVC" reference?

**Comment by jpiesing** [comment]
https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/edit#gid=0

**Comment by jpiesing** [comment]
The terminology is copied from the WAVE device playback spec.

**Comment by rbouqueau** [comment]
I think the important bit here is not the presence of B-Frames or the fragmentation at P-Frames. I think what we are trying to check is multiple ISOBMFF fragments per segment, correct?

If so, I suggest to change the wording of the sparse matrix.

Long story short, supporting "p-frame to p-frame with b-frames" in a generic way would be a permanent hack in the current code.

**Comment by jpiesing** [comment]
The origin of this text is section 10.2.3 of the DPCTF specification.

![image](https://user-images.githubusercontent.com/8490792/176627946-6a01df54-ea82-4bc3-8257-b90e9376074a.png)

This does explicitly reference B-frames. @haudiobe, I assume you wrote this?

**Comment by rbouqueau** [comment]
So I've added B-frames with fragment duration based on the number of B-frames in that case.

**Comment by rbouqueau** [comment]
There was still an issue in the fragment duration computation. Should be solved by 32f04dd34d8f701edd7f4be068d5522e22a5cb9b.

**Comment by nicholas-fr** [comment]
Resolved in the latest test content, see https://github.com/cta-wave/Test-Content/issues/40#issuecomment-1310031376.
I believe this issue can be closed.

**Comment by gitwjr** [comment]
2022-11-22: Closed based on Nicholas' validation testing of 2022-10-17 test vectors release.
