### ISSUE TITLE
documentation on how audio streams were encoded and packaged

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content-Generation#58]
In the December 6th meeting, we had a discussion about issue https://github.com/cta-wave/Test-Content-Generation/issues/3 which relates to properly documenting how a stream was encoded and packaged so it can be re-generated several years later if a problem is found. The conclusion was that we have most of this for video and what's left can be deferred. Fundamentally the AVC streams can be regenerated using open source tools and scripts that are in this repo.

Eurofins need to decide how this issue will be addressed for audio. What documentation will they provide for how to re-generate the audio they are/will be encoding and packaging. What scripts will be provided in this repo? They may be using commercial tools & not open source. They may be using pre-release or R&D versions of commercial tools. All that makes reproducing the encoding in the future complex but it is important.

**Comment by rbouqueau** [comment]
FYI the DTS/XPERI streams are generated using this repository, see https://github.com/cta-wave/Test-Content-Generation#audio-content-xperidts

**Comment by rcottingham** [comment]
@rbouqueau I can update the Readme with this info and submit to you for review or provide to you update. Let me know the best approach please.

**Comment by rbouqueau** [comment]
Any approach works: modify the Readme or provide a PR.

**Comment by mbergman42** [comment]
I'm doing theory of operation, but not how to regenerate the test material. Richard, I'll send you a draft on the side.

**Comment by jpiesing** [comment]
A solution of this has been proposed at https://github.com/cta-wave/Test-Content-Generation/pull/67

**Comment by rcottingham** [comment]
[Pull request](https://github.com/cta-wave/Test-Content-Generation/pull/67) merged. I believe this can now be closed.

**Comment by rbouqueau** [comment]
Agreed. We now need to make decisions in #66 .
