### ISSUE TITLE
Typo in AdaptationSet@initializationPrincipal in switching set MPD

### ISSUE THREAD

**Issue by nicholas-fr** [cta-wave/Test-Content-Generation#59]
Seen in http://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/avc_15_30_60_ss1_stream_v4.mpd

`AdaptationSet@initializationPrincipale` instead of `AdaptationSet@initializationPrincipal` without the last 'e'.

**Comment by rbouqueau** [comment]
Cf https://github.com/cta-wave/Test-Content-Generation/search?q=initializationPrinciple for places to modify.
