### ISSUE TITLE
Switching Set (ss1) MPD points to wrong location for media segments

### ISSUE THREAD

**Issue by nicholas-fr** [cta-wave/Test-Content-Generation#60]
Currently the ss1 MPDs point to the <stream_ID> sub-folder (e.g. t19) for the media segments, but the actual test streams are in the <stream_ID>/<upload_date> sub-folder.

Example:
- ss1 points to: `cfhd_sets/14.985_29.97_59.94/t19`
- expected: `cfhd_sets/14.985_29.97_59.94/t19/2022-10-17`

**Comment by rbouqueau** [comment]
Sorry I must have missed something.

I took the first ss1 in the [database](https://cta-wave.github.io/Test-Content/database.json): https://dash.akamaized.net/WAVE/vectors/cfhd_sets/12.5_25_50/ss1/2022-10-17/avc_12.5_25_50_ss1_stream_v4.mpd

If I look online, I see: https://dash.akamaized.net/WAVE/vectors/cfhd_sets/12.5_25_50/ss1/2022-10-17/cfhd_sets/12.5_25_50/t19/

If I unzip the archive, I see:
```
 creating: cfhd_sets/12.5_25_50/t19/
```

What is the issue?

Note that the ss1 itself is in a "2022-10-17" folder e.g. "https://dash.akamaized.net/WAVE/vectors/cfhd_sets/12.5_25_50/ss1/2022-10-17/".

**Comment by nicholas-fr** [comment]
Sorry if I wasn't clear. The MPD expects the segments to be located in the tN folders.
E.g. cfhd_sets/14.985_29.97_59.94/t19/init.mp4
`<AdaptationSet segmentAlignment="true" maxWidth="1920" maxHeight="1080" maxFrameRate="60" par="16:9" lang="und" startWithSAP="1" contentType="video" containerProfiles="'cmf2','cfhd'" initializationPrinciple="cfhd_sets/15_30_60/t19/init.mp4" >`

And the segments are indeed in that folder in the ss1.zip files.

So the upload_date sub-folder is missing from the ss1 folder structure in the MPDs and zips.

**Comment by rbouqueau** [comment]
> So the upload_date sub-folder is missing from the ss1 folder structure in the MPDs and zips.

Yes, that's intended. As I wrote above: "Note that the ss1 itself is in a "2022-10-17" folder e.g. https://dash.akamaized.net/WAVE/vectors/cfhd_sets/12.5_25_50/ss1/2022-10-17/". So the full path of the txx (e.g. t19) content contains the date.

Is it an issue for you, or were you just surprised that the folder structure was different in this case?

**Comment by nicholas-fr** [comment]
>Yes, that's intended.
>Is it an issue for you, or were you just surprised that the folder structure was different in this case?

Neither, it just doesn't match with the agreed structure. 
I don't think it makes sense to have duplicates of the same test streams, or to have a mix of chdf and cfhd within the cfhd_sets folder.
If this is a concern, happy to discuss/clarify.

I expected the following:
`https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/ss1.zip`
and when extracting ss1.zip for AVC 15_30_60:
```
https://dash.akamaized.net/WAVE/vectors/avc_15_30_60_ss1_stream.mpd
```
referencing:
```
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t19/2022-10-17/1/init.mp4
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t19/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/chdf_sets/15_30_60/t20/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t23/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t24/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t25/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t28/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t32/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t34/2022-10-17/1/$Time$.m4s
```
I.e. using the same media segments as the single representation test streams.

And it seems that we have:
`https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/ss1.zip`
intended to be extracted as:
```
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/avc_15_30_60_ss1_stream.mpd
```
referencing:
```
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/cfhd_sets/15_30_60/t19/init.mp4
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/cfhd_sets/15_30_60/t19/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/chdf_sets/15_30_60/t20/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/cfhd_sets/15_30_60/t23/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/cfhd_sets/15_30_60/t24/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/cfhd_sets/15_30_60/t25/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/cfhd_sets/15_30_60/t28/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/cfhd_sets/15_30_60/t32/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/cfhd_sets/15_30_60/t34/$Time$.m4s
```

**Comment by rbouqueau** [comment]
> Neither, it just doesn't match with the agreed structure.

I don't mind changing the structure. However I don't feel like the agreed structure would have to apply to any sub-structure. The current choice is just trying to avoid name collisions.

> I don't think it makes sense to have duplicates of the same test streams

I agree, but this is what was decided during the calls. That's because eventually or switching sets could refer to audio streams etc. that could be accidentally moved or deleted ; we would not know which ss depends on which test stream.

> or to have a mix of chdf and cfhd within the cfhd_sets folder.

I think having ss1 using both raises the question of where ss1 belongs. I mentioned it in a call and I was told to put it anywhere, so I put it in cfhd. But where would we put it once we integrate audio etc.?

I am not against re-opening this discussion. Its' just that at this point I don't understand which problems we are trying to solve.

**Comment by rbouqueau** [comment]
@rbouqueau Do not use duplicate copies of the content anymore in the mpd. But the zip would contain all the necessary content.

@nicholas-fr Where do we put ss1? In the vector/ folder, unless told otherwise. Please confirm.

**Comment by rbouqueau** [comment]
Waiting for the confirmation this is ok to update the content.

**Comment by nicholas-fr** [comment]
I propose to use the following structure and MPD name for ss1 and other stream IDs that use media segments from the single representation test streams (t1..t34):
`<codec>/<frame_rate_family>/<stream_id>/<upload_date>/<stream_id>.zip`
`<codec>/<frame_rate_family>/<stream_id>/<upload_date>/stream.mpd`
e.g. https://dash.akamaized.net/WAVE/vectors/avc/15_30_60/ss1/2022-10-17/ss1.zip
e.g. https://dash.akamaized.net/WAVE/vectors/avc/15_30_60/ss1/2022-10-17/stream.mpd

Where the MPD references (via relative reference) the same media segments as the single representation test streams:

```
https://dash.akamaized.net/WAVE/vectors/avc/15_30_60/ss1/2022-10-17/stream.mpd

https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t19/2022-10-17/1/init.mp4
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t19/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/chdf_sets/15_30_60/t20/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t23/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t24/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t25/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t28/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t32/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t34/2022-10-17/1/$Time$.m4s
```

**Comment by nicholas-fr** [comment]
To clarify, this proposal would:
- Change the ss1 MPD name
- Change the ss1 zip and MPD location (folder structure).

Currently we have:

https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/ss1.zip
intended to be extracted as:

https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/avc_15_30_60_ss1_stream.mpd
referencing:

https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/cfhd_sets/15_30_60/t19/init.mp4
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/cfhd_sets/15_30_60/t19/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/chdf_sets/15_30_60/t20/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/cfhd_sets/15_30_60/t23/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/cfhd_sets/15_30_60/t24/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/cfhd_sets/15_30_60/t25/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/cfhd_sets/15_30_60/t28/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/cfhd_sets/15_30_60/t32/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/ss1/2022-10-17/cfhd_sets/15_30_60/t34/$Time$.m4s


With the proposal in the folder structure, "cfhd_sets" would change to "avc", and the MPD filename would change from "avc_15_30_60_ss1_stream.mpd" to "stream.mpd" and would be extracted to the ss1/<upload_date> folder, using the same approach as t1..t34:

https://dash.akamaized.net/WAVE/vectors/avc/15_30_60/ss1/2022-10-17/ss1.zip
intended to be extracted as:

https://dash.akamaized.net/WAVE/vectors/avc/15_30_60/ss1/2022-10-17/stream.mpd
referencing: 

https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t19/2022-10-17/1/init.mp4
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t19/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/chdf_sets/15_30_60/t20/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t23/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t24/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t25/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t28/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t32/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t34/2022-10-17/1/$Time$.m4s

**Comment by rbouqueau** [comment]
Two questions:
1. What happens when a switching set contains several codecs? Why not use a ```switching_sets/``` folder instead of ```codec/```? (I realize we would then have to handle switching sets "naming/ordering" with a global approach)
1. Is it ok for everyone to have absolute URLs in the MPD? @nicholas-fr do you confirm it is what you intent? or do we expect people to extract the other zips as well?

**Comment by nicholas-fr** [comment]
@rbouqueau 
Regarding 1, I was thinking we would always use the "main" codec as the reference point, e.g. the AVC codec switching test would be under avc/* even if it uses the same tracks and media segments as the HEVC codec switching test.
It might be harder to manage unique switching set naming globally.

Regarding 2, I'm not proposing to change the referencing, I would propose to continue using relative URLs. 
Likewise, the zips (e.g. ss1.zip) could be extracted to the root folder (vectors) and would contain the MPD and the media segments. Unless there are concerns with that.

**Comment by rbouqueau** [comment]
Agreement from today's goal:
1. replace ```avc/``` by ```switching_sets/```
2. the server folder only contains the mpd (with relative URLs) and a zip (containing the same MPD + the content from the relative vectors)

This would give:

https://dash.akamaized.net/WAVE/vectors/switching_sets/15_30_60/ss1/2022-10-17/stream.mpd
and 
https://dash.akamaized.net/WAVE/vectors/switching_sets/15_30_60/ss1/2022-10-17/ss1.zip

intended to be extracted as:

https://dash.akamaized.net/WAVE/vectors/switching_sets/15_30_60/ss1/2022-10-17/stream.mpd

referencing:

https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t19/2022-10-17/1/init.mp4
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t19/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/chdf_sets/15_30_60/t20/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t23/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t24/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t25/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t28/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t32/2022-10-17/1/$Time$.m4s
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t34/2022-10-17/1/$Time$.m4s

@nicholas-fr Please confirm this is ok and I will regenerate.

**Comment by nicholas-fr** [comment]
@rbouqueau Thanks Romain, that matches my understanding, OK for me.

**Comment by rbouqueau** [comment]
Updated and uploaded!

**Comment by gitwjr** [comment]
@nicholas-fr to validate. Once done this issue and https://github.com/nicholas-fr/test-content-validation/issues/15 can be closed.

**Comment by gitwjr** [comment]
Close. @nicholas-fr can reopen if it has not been validated.
