### ISSUE TITLE
changes to sparse matrix for AVC

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content-Generation#61]
This issue is to track proposals for changes to the sparse matrix for AVC.

https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/edit?usp=sharing

I have the following 2 changes in mind.
- Long duration is not included. That could just be added as a new column.
- Encrypted content is not included. We would probably want to add a new row for cenc/cbcs as well as a some new columns. If you look at 8.12, 8.13 and 8.14, I suspect they may all need different encrypted streams. 8.12 could use an encrypted version of t1. 8.13 might need an encrypted version of the streams from 8.8. 8.14 sounds like a hybrid between 8.8 and 8.13, i.e. it would not have any new stream requirements.

@nicholas-fr @rbouqueau What do you think of the two changes proposed above? Do you have other changes you would like to see?

**Comment by rbouqueau** [comment]
At first sight it looks good to me. Eventually we would also need to review and add the requirements for other codecs (starting with HEVC as needed for https://github.com/cta-wave/Test-Content/issues/38).

**Comment by nicholas-fr** [comment]
>I have the following 2 changes in mind.

I have the same understanding. 
On that basis there would be 4 new columns to add:
- ld1 (1080p framerate 0.5 duration 7200s - with the same other parameters as t1?)
- t1_cenc
- splice_main_cenc
- splice_ad_cenc
As long as if 8.14 can use the combination of splice_main_cenc and splice_ad (or splice_main and splice_ad_cenc).

**Comment by jpiesing** [comment]
Done.
