### ISSUE TITLE
AVC test stream with audio

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/Test-Content-Generation#62]
We have two tests ("Regular Playback of a CMAF Presentation" and "Random Access of a WAVE Presentation") that, by definition, need a stream with AVC and audio. Historically t1 included audio even though it wasn't needed and these tests just use t1 assuming the MPD includes both video and audio.

What is simplest?
- Restore the audio in t1
- Restore the audio in all AVC adaptation sets
- Define a new stream which is the same as t1 but with audio

Which audio? The audio from the mezzanine or the PN audio? @cta-source  do you have an opinion?
@yanj-github @rcottingham What does the OF need for the two tests of WAVE presentations?

**Comment by rbouqueau** [comment]
> Define a new stream which is the same as t1 but with audio

I would opt for this. I can assemble a manifest if no-one downstream is able to do it.

FYI the old ```caac``` audio set based on the mezzanine audio still exists. I just don't have uploaded it because I thought it would be superseeded by Resilion's streams. Please update me on which stream to use when decided.

**Comment by mbergman42** [comment]
This may be overtaken by events, but to answer the question, I'd strongly recommend using the PN audio for tests because it is needed for automation in the future (not planned for first launch, but after).

**Comment by FritzHeiden** [comment]
I added audio to the affected tests according to Resillions spread sheet
https://github.com/cta-wave/dpctf-tests/issues/111#issuecomment-1545809999

**Comment by gitwjr** [comment]
Closed. This is captured by DPCTF-tests #111
