### ISSUE TITLE
t32 B1 512x288 vectors have encoding artefacts rendering QR codes unreadable

### ISSUE THREAD

**Issue by nicholas-fr** [cta-wave/Test-Content-Generation#63]
New versions of t32 vectors are needed, so that their QR codes are readable.
Currently they have encoding artefacts (macroblocking).
Applies to all 3 framerate families.

Examples of unreadable QR codes:

![vlcsnap-2023-08-29-14h19m45s316](https://github.com/cta-wave/Test-Content-Generation/assets/9865551/eb928866-8939-4fde-9e08-e34c8eb9ba1b)

![vlcsnap-2023-08-29-14h23m59s745](https://github.com/cta-wave/Test-Content-Generation/assets/9865551/e7a8b72f-08a6-45d7-a59c-24fe9e85799f)

**Comment by rbouqueau** [comment]
I can see the issue. In fact all streams (not only t32 and splice ad #63) look sub-quality to my eyes compare to what they were in the previous batch.

**Comment by yanj-github** [comment]
Is this related to previous issue that we have raised https://github.com/cta-wave/Test-Content/issues/28 as well?

**Comment by rbouqueau** [comment]
It seems. It's just that nobody seemed to have had a look at the video at that time.

**Comment by rbouqueau** [comment]
FYI I can reproduce by only downgrading FFmpeg to the previous version. So it seems it is not only a bitrate problem (which would be confirmed by the file sizes).

Currently re-encoding. I'll let you know how it looks.

**Comment by jpiesing** [comment]
@nicholas-fr and I did discuss extending his script to check that at least one QR code can be extracted from every frame. It would massively increase the execution time for the script though.

**Comment by rbouqueau** [comment]
> @nicholas-fr and I did discuss extending his script to check that at least one QR code can be extracted from every frame. It would massively increase the execution time for the script though.

According to this comment https://github.com/cta-wave/Test-Content/issues/28#issuecomment-1307532110, t34 or t32 would be good candidates for such a test.

**Comment by rbouqueau** [comment]
Could you please test with the new URL (2023-91-01 batch) and confirm it works for you?

**Comment by nicholas-fr** [comment]
@rbouqueau The newly generated streams (2023-09-01) have resolved the encoding issues for t32.
