### ISSUE TITLE
splice_ad AD-A1 vectors have encoding artefacts rendering QR codes difficult to read in test recordings

### ISSUE THREAD

**Issue by nicholas-fr** [cta-wave/Test-Content-Generation#64]
New versions of splice_ad vectors are needed, so the QR codes are less difficult to read.
Currently they have some encoding artefacts (macroblocking), which render some of the QR codes more difficult to read, especially in device screen recordings.

Applies to all 3 framerate families.

Examples:

![vlcsnap-2023-08-29-14h42m35s250](https://github.com/cta-wave/Test-Content-Generation/assets/9865551/9ba28491-3ce1-4951-836c-224626619f60)

![image](https://github.com/cta-wave/Test-Content-Generation/assets/9865551/29ea59c0-99d2-481b-9b8e-583078973736)

**Comment by rbouqueau** [comment]
Could you please test with the new URL (2023-91-01 batch) and confirm it works for you?

**Comment by jpiesing** [comment]
@nicholas-fr Please can you check if these new batches appear OK.

**Comment by jpiesing** [comment]
Is there an encrypted version of this as well? Does that have the same issues? The results suggest it might.

**Comment by rbouqueau** [comment]
I re-regenerated all the stream (so that includes also the encrypted ones + ss1 + chunked).

**Comment by nicholas-fr** [comment]
The re-encoded streams resolve #63.
The splice_* streams were not regenerated, but I assume the same fix will work equally well for them.

**Comment by rbouqueau** [comment]
They were:
- https://dash.akamaized.net/WAVE/vectors/cfhd_sets/12.5_25_50/splice_ad/2023-09-01
- https://dash.akamaized.net/WAVE/vectors/cfhd_sets/12.5_25_50/splice_ad-cenc/2023-09-01
- https://dash.akamaized.net/WAVE/vectors/cfhd_sets/12.5_25_50/splice_main/2023-09-01
- https://dash.akamaized.net/WAVE/vectors/cfhd_sets/12.5_25_50/splice_main-cenc/2023-09-01

**Comment by nicholas-fr** [comment]
Thanks, I was indeed looking in the wrong place.... 
I've checked splice_ad and splice_main and they look OK.

**Comment by jpiesing** [comment]
Closing as I have a recording with the correct content.
