### ISSUE TITLE
MPD for Content Model not parsing CMAF Header

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/Test-Content-Generation#7]
At this stage the MPD generated for the content model is not parsing the CMAF header to extract the relevant parameters. This may actually result in the case that the MPD is not conforming to the content model and may run into a conformance issue.

The parsing of the CMAF header should be added eventually to generate the MPD.

This script is also needed to the DASH Profile for CMAF content done in MPEG.

**Comment by gitwjr** [comment]
Overtaken by events. GPAC is used to encode and generate the MPD. 
Close.
