### ISSUE TITLE
CMAF Test Stream Documentation

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/Test-Content-Generation#9]
Determine list of CMAF test streams to create and the annotated mezzanine content to use for each of them.

We need a single document, web page, to aggregate all of this information.

**Comment by jpiesing** [comment]
This is the document from before with the old material (mezzanine content annotation) removed.
[wave-device-playback-stream-production-annotation-2020-07-29.docx](https://github.com/cta-wave/Test-Content-Generation/files/4995991/wave-device-playback-stream-production-annotation-2020-07-29.docx)

**Comment by jpiesing** [comment]
My understanding of the discussion on July 29th was that it was desirable to have both
1) a minimum set of streams which exercise each option and
2) a set of streams that differ from a baseline by only one option
Normally the minimum set would be used but when something doesn't work, the set that differ from the baseline by just one option would help focus in on where the problem is.

**Comment by jpiesing** [comment]
I made a list of streams in this project's Wiki.
https://github.com/cta-wave/Test-Content-Generation/wiki/AVC-test-streams
It may be easier to review than the Word file.

**Comment by yanj-github** [comment]
We made a contents options and E-AC-3 and AC-4 streams' list based on our understandings of the instructions and what had been done for AVC test streams and AAC. The document is attached. Let us know if you have any comments. 
[E-AC-3 and AC-4 Test Streams.docx](https://github.com/cta-wave/Test-Content-Generation/files/5622133/E-AC-3.and.AC-4.Test.Streams.docx)

**Comment by jpiesing** [comment]
> We made a contents options and E-AC-3 and AC-4 streams' list based on our understandings of the instructions and what had been done for AVC test streams and AAC. The document is attached. Let us know if you have any comments.

I'm not really qualified to comment but one thing I notice is the fragment duration of 2s. I believe in other places, 960ms has been mentioned as a common short fragment duration and 4*960ms = 3.84s as a common longer fragment duration.

**Comment by yanj-github** [comment]
> 
> 
> > We made a contents options and E-AC-3 and AC-4 streams' list based on our understandings of the instructions and what had been done for AVC test streams and AAC. The document is attached. Let us know if you have any comments.
> 
> I'm not really qualified to comment but one thing I notice is the fragment duration of 2s. I believe in other places, 960ms has been mentioned as a common short fragment duration and 4*960ms = 3.84s as a common longer fragment duration.

Thanks for your comment Jon, can you tell me where do you get this from please? Idont think we heard if this and couldnt find this online either.

**Comment by jpiesing** [comment]
DVB DASH 4.5 says the following;

> Segment duration shall be at least 960 ms, except for the last segment of a Period which may be shorter.
> NOTE: This value is chosen to be close to one second. The specific value is a favourable duration for the
> alignment of audio and video chunk durations in 50 Hz systems, based on typical audio frame duration
> and efficient video GOP structures.

It used to be 1s but was changed to 960ms and the note was added.

**Comment by yanj-github** [comment]
> 
> 
> DVB DASH 4.5 says the following;
> 
> > Segment duration shall be at least 960 ms, except for the last segment of a Period which may be shorter.
> > NOTE: This value is chosen to be close to one second. The specific value is a favourable duration for the
> > alignment of audio and video chunk durations in 50 Hz systems, based on typical audio frame duration
> > and efficient video GOP structures.
> 
> It used to be 1s but was changed to 960ms and the note was added.

Thanks Jon for the information, does 960ms then become incompatible with the video that is already generated? The 2s duration was taken from the AVC video and also the AAC audio wiki also state that it is 2s.

**Comment by IngoIIS** [comment]
> > DVB DASH 4.5 says the following;
> > > Segment duration shall be at least 960 ms, except for the last segment of a Period which may be shorter.
> > > NOTE: This value is chosen to be close to one second. The specific value is a favourable duration for the
> > > alignment of audio and video chunk durations in 50 Hz systems, based on typical audio frame duration
> > > and efficient video GOP structures.
> > 
> > 
> > It used to be 1s but was changed to 960ms and the note was added.
> 
> Thanks Jon for the information, does 960ms then become incompatible with the video that is already generated? The 2s duration was taken from the AVC video and also the AAC audio wiki also state that it is 2s.

The AAC values are placeholders at the moment. I would suggest to follow DVB for the lower boundary. Is there a best practice for the upper values, something around 5-10 seconds? Would this even be relevant for what we're trying to achieve here?

**Comment by jpiesing** [comment]
> The AAC values are placeholders at the moment. I would suggest to follow DVB for the lower boundary. Is there a best practice for the upper values, something around 5-10 seconds? Would this even be relevant for what we're trying to achieve here?

Here is the logic behind the 960ms value from @RufaelDev

> As 0,96 s * 25 fp/s = 24 video frames per segment
> As 48000khz/1024 frames per sample * 0,96 = 45 samples/segment
> 
> So with these durations you can get perfect alignment, 

It is suggested this might be specific to AAC though.

**Comment by RufaelDev** [comment]
Advantage of 960 ms and multiples is that you can achieve fragment boundary alignment for aac (45)  and e-ac3 (30) for ac-4 the audio video alignment is built in (audio samples can have the same duration as video frames)

**Comment by IngoIIS** [comment]
> Advantage of 960 ms and multiples is that you can achieve fragment boundary alignment for aac (1024 per iso sample-> 45 per fragment) and e-ac3 (1536 per iso sample -> 30 fragment) for ac-4 the audio video alignment is built in (audio samples can have the same duration as video frames)

Same for MPEG-H Audio, that allows flexible segment lengths. I believe the discussion here is more about legacy audio codecs and resonable settings for test content.

**Comment by gitwjr** [comment]
@haudiobe 
There is an folder https://github.com/cta-wave/Test-Content-Generation/tree/master/Instructions. Is it now up to date or does more need to be done? 
Peter will check with Yan to determine how it is done. We need to figure out what official reference is to be used to generate the content.

**Comment by jpiesing** [comment]
This issue can be closed. The list needed is per codec. We have done this for AVC in the sparse matrix google doc. It needs doing for each new codec as part of the process of adding that codec. Similar lists exist for the audio codecs at https://github.com/cta-wave/Test-Content/issues/27, https://github.com/cta-wave/Test-Content/issues/26 and https://github.com/cta-wave/Test-Content/issues/25.
